# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fav_by',
            field=models.ManyToManyField(related_name='favorites', to='main.User'),
        ),
    ]
