# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_fav_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.TextField(),
        ),
    ]
