# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191024_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='year_round',
            field=models.CharField(max_length=5),
        ),
    ]
