# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes'),
            preserve_default=False,
        ),
    ]
